Publish statistics through MetricQ
metricq/metricq-db-hta pull request #20
Opened 2021-05-07 09:18 UTC by tilsche

Briefly tested it and it seemed to work so far.

Unfortunately the wizard can't configure the created metrics because their source is a db... So that will be another issue.

fixes #19

2021-05-10 12:33 UTC, bmario requested changes

2021-05-10 12:33 UTC, bmario commented on src/db_stats.cpp
> +        pending_count_.send({ time, (double)stats.pending_count_ });
Don't C-style cast

2021-05-10 12:33 UTC, bmario commented on src/db_stats.cpp
> +        active_count_.metadata.description("number of actively processed {}-requests");
Looks like a missing fmt::format or something.

2021-05-10 12:33 UTC, bmario commented on src/db_stats.cpp
> +        auto read_stats = read.collect();
I feel like these locals should be inline instead.

2021-05-10 12:33 UTC, bmario commented on src/db_stats.cpp
> +    metricq::TimePoint previous_dump_time_;
This variable is never read and only set once in the constructor.

2021-05-10 12:36 UTC, bmario reviewed
Also, I haven't seen a `declare_metrics()` call.

2021-05-10 12:45 UTC, tilsche commented
> Also, I haven't seen a `declare_metrics()` call.

That's done in the base class
https://github.com/metricq/metricq-cpp/blob/experimental-async-cpp-db/src/db.cpp#L199

2021-05-10 18:54 UTC, tilsche commented
I believe I have addressed all the review comments.

2021-05-11 07:43 UTC, bmario approved these changes

2021-05-11 11:10 UTC, merged